# Generated by Django 3.2.14 on 2022-10-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_donation_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="social_image",
            field=models.ImageField(blank=True, upload_to="posts/social/"),
        ),
    ]
