# Generated by Django 3.2.14 on 2023-06-10 13:39

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_post_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_purchaseable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="minimum_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default=Decimal("0"), max_digits=7
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="minimum_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("INR", "Indian Rupee")],
                default="INR",
                editable=False,
                max_length=3,
            ),
        ),
    ]
