# Generated by Django 3.2.14 on 2023-12-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_pinned_in_section',
            field=models.BooleanField(default=False),
        ),
    ]
