[bumpver]
current_version = "2023.04.1140"
version_pattern = "YYYY.0M.BUILD"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[bumpver.file_patterns]
"dev.yml" = [
    '    image: v1k45/fanmo:{version}-dev',
]
"production.yml" = [
    '    image: v1k45/fanmo:{version}',
]
"bumpver.toml" = [
    'current_version = "{version}"',
]
