version: '3.9'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    image: v1k45/fanmo:2022.07.1071
    volumes:
      - ./backend/fanmo/media:/app/fanmo/media
    depends_on:
      - postgres
      - redis
    networks:
      - backend
      - proxy
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.nuxt
      - ./.envs/.dev/.postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/meta/"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 50

  postgres:
    image: postgres:13.2-alpine
    container_name: memberships_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.dev/.postgres
    networks:
      - backend
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 50

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: memberships_mailhog
    ports:
      - "8025:8025"
    networks:
      - backend

  redis:
    image: redis:6-alpine
    container_name: memberships_redis
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 50

  caddy:
    image: "caddy:2.1.1"
    restart: unless-stopped
    depends_on:
      - django
    env_file: ./.envs/.dev/.caddy
    container_name: memberships_caddy
    volumes:
      - ./Caddyfile.local:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./backend/fanmo/media:/var/www/html/media
    ports:
      - "7070:80"
      - "7777:443"
    networks:
      - proxy

networks:
  backend:
    driver: overlay
  proxy:
    driver: overlay
