version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    image: v1k45/fanmo:dev-latest
    volumes:
      - ./backend/memberships/media:/app/memberships/media
    depends_on:
      - postgres
      - mailhog
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.nuxt
      - ./.envs/.dev/.postgres
    ports:
      - "8801:8000"
    command: /start

  qcluster:
    <<: *django
    ports: []
    command: /qcluster

  nuxt:
    <<: *django
    ports: []
    command: /nuxt

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: memberships_production_postgres
    container_name: memberships_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.dev/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: memberships_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: memberships_redis

  caddy:
    image: "caddy:2.1.1"
    restart: unless-stopped
    depends_on:
      - django
    env_file: ./.envs/.dev/.caddy
    container_name: memberships_caddy
    volumes:
      - ./Caddyfile.local:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    ports:
      - "7070:80"
      - "7777:443"
