version: '3.9'

services:
  django: &django
    image: v1k45/fanmo:2023.04.1150
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.prod/.django
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/meta/"]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 50
    logging:
      driver: awslogs
      options:
        awslogs-group: fanmo
        awslogs-create-group: "true"
