version: '3'

volumes:
  production_postgres_data: {}

services:
  django: &django
    image: v1k45/fanmo:latest
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.prod/.django
      - ./.envs/.local/.postgres
    command: /start

  qcluster:
    <<: *django
    ports: []
    command: /qcluster

  nuxt:
    <<: *django
    ports: []
    command: /nuxt

  caddy:
    image: "caddy:2.1.1"
    restart: unless-stopped
    depends_on:
      - django
      - nuxt
    env_file: ./.envs/.local/.caddy
    volumes:
      - ./Caddyfile.local:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./build:/var/www/html
    ports:
      - "80:80"
      - "443:443"

  redis:
    image: redis:6

  postgres:
    image: postgres:13.2
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/.local/.postgres
