# Generated by Django 3.2.8 on 2021-11-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_alter_donation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="external_id",
            field=models.CharField(max_length=255),
        ),
    ]
