# Generated by Django 3.2.8 on 2022-04-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0007_auto_20220401_0514"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="message",
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name="historicaldonation",
            name="message",
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
