# Generated by Django 3.2.8 on 2022-07-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0008_auto_20220406_0700"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaldonation",
            name="ip_address",
            field=models.GenericIPAddressField(null=True, verbose_name="IP address"),
        ),
    ]
