# Generated by Django 3.2.14 on 2023-06-10 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_post_purchase"),
        ("donations", "0003_auto_20220725_0043"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="post",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="historicaldonation",
            name="post",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="posts.post",
            ),
        ),
    ]
