# Generated by Django 3.2.14 on 2022-07-24 19:13

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorUser",
            fields=[],
            options={
                "db_table": "creator_users",
                "ordering": ("-created_at",),
                "proxy": True,
                "default_related_name": "creator_users",
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="historicaluserpreference",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical user preference",
                "verbose_name_plural": "historical user preferences",
            },
        ),
        migrations.AlterField(
            model_name="historicaluserpreference",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
