# Generated by Django 3.2.14 on 2022-12-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_social_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
