# Generated by Django 3.2.14 on 2022-12-08 07:29

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserpreference",
            name="default_donation_amount",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("50.0"),
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaluserpreference",
            name="default_donation_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("INR", "Indian Rupee")],
                default="INR",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaluserpreference",
            name="enable_donation_tiers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="default_donation_amount",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("50.0"),
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="default_donation_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("INR", "Indian Rupee")],
                default="INR",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="enable_donation_tiers",
            field=models.BooleanField(default=False),
        ),
    ]
