# Generated by Django 3.2.8 on 2021-10-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_auto_20211028_0636"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="cycle_end_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="cycle_start_at",
            field=models.DateTimeField(),
        ),
    ]
