# Generated by Django 3.2.8 on 2021-11-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_auto_20211029_0748"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("card", "Card"),
                    ("emandate", "Emandate"),
                    ("upi", "Upi"),
                    ("wallet", "Wallet"),
                ],
                max_length=16,
            ),
        ),
    ]
