# Generated by Django 3.2.8 on 2021-11-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_subscription_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="scheduled_to_change",
            field=models.BooleanField(default=False),
        ),
    ]
