# Generated by Django 3.2.8 on 2022-03-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_auto_20220225_0632"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tier",
            old_name="seller_user",
            new_name="creator_user",
        ),
        migrations.AddField(
            model_name="tier",
            name="is_recommended",
            field=models.BooleanField(default=False),
        ),
    ]
