# Generated by Django 3.2.8 on 2022-03-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_auto_20220317_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='benefits',
        ),
    ]
