# Generated by Django 3.2.8 on 2022-05-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0011_historicalmembership_historicalsubscription_historicaltier",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltier",
            name="cover_background_style",
            field=models.CharField(
                choices=[("contain", "Contain"), ("cover", "Cover")],
                default="contain",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="tier",
            name="cover_background_style",
            field=models.CharField(
                choices=[("contain", "Contain"), ("cover", "Cover")],
                default="contain",
                max_length=16,
            ),
        ),
    ]
