# Generated by Django 3.2.8 on 2022-06-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0012_auto_20220513_0408"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tier",
            options={
                "default_related_name": "tiers",
                "ordering": ["creator_user", "amount"],
            },
        ),
    ]
