# Generated by Django 3.2.8 on 2022-07-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0013_alter_tier_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmembership",
            name="ip_address",
            field=models.GenericIPAddressField(null=True, verbose_name="IP address"),
        ),
        migrations.AddField(
            model_name="historicalsubscription",
            name="ip_address",
            field=models.GenericIPAddressField(null=True, verbose_name="IP address"),
        ),
        migrations.AddField(
            model_name="historicaltier",
            name="ip_address",
            field=models.GenericIPAddressField(null=True, verbose_name="IP address"),
        ),
    ]
