# Generated by Django 3.2.8 on 2022-07-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0015_auto_20220716_0445"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="interval",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="plan",
            name="period",
            field=models.CharField(
                choices=[
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                default="monthly",
                max_length=16,
            ),
        ),
    ]
