# Generated by Django 3.2.8 on 2022-07-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sender",
                    models.CharField(choices=[("razorpay", "Razorpay")], max_length=15),
                ),
                ("payload", models.JSONField()),
                ("is_processed", models.BooleanField(default=False)),
                ("external_id", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "webhook_messages",
                "ordering": ("-created_at",),
                "default_related_name": "webhook_messages",
            },
        ),
    ]
