# Generated by Django 3.2.14 on 2022-09-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discorduser",
            name="external_id",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
