# Generated by Django 3.2.14 on 2022-10-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_discorduser_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordserver",
            name="kick_inactive_members",
            field=models.BooleanField(default=False),
        ),
    ]
