import re

from django.http.response import HttpResponse

from fanmo.posts.models import Post
from fanmo.users.models import User


def index_view(request, *args, **kwargs):
    return serve_index()


def handle_404(request, *args, **kwargs):
    return serve_index(title="Page not Found", status=404)


def handle_400(request, *args, **kwargs):
    return serve_index(title="Bad Request", status=400)


def handle_500(request, *args, **kwargs):
    return serve_index(title="Internal Server Error", status=404)


def handle_403(request, *args, **kwargs):
    return serve_index(title="Permission Denied", status=404)


def page_view(request, username):
    user = User.objects.filter(
        username=username, is_creator=True, is_active=True
    ).first()
    if not user:
        return serve_index(status=404)

    return serve_index(
        f"{user.display_name} {user.one_liner}",
        f"Support {user.display_name} on Fanmo. Become a member, get access to exclusive content, send donations and much more on Fanmo.",
    )


def post_view(request, post_slug, post_id):
    post = Post.objects.filter(id=post_id, is_published=True).first()
    if not post:
        return serve_index(status=404)

    return serve_index(
        f"{post.title} - {post.author_user.display_name}",
        f"Support {post.author_user.display_name} on Fanmo. Become a member, get access to exclusive content, send donations and much more on Fanmo.",
    )


def serve_index(title=None, description=None, status=200):
    """
    Serve and manipulate 200.html generated by nuxt.
    """
    response_text = open("/var/www/html/200.html").read()
    if title:
        title_template = "<title>%s</title>"
        response_text = re.sub(
            title_template % "(.*)",
            title_template % f"{title.strip()} | Fanmo",
            response_text,
            1,
        )

    if description:
        description_template = 'name="description" content="%s" data-hid="description"'
        response_text = re.sub(
            description_template % "(.*)",
            description_template % description,
            response_text,
            1,
        )
    return HttpResponse(response_text, "text/html", status=status)
