# Generated by Django 3.2.8 on 2021-10-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20211028_0636"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"default_related_name": "users", "ordering": ("-created_at",)},
        ),
    ]
