# Generated by Django 3.2.8 on 2022-03-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_useronboarding_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="one_liner",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
