# Generated by Django 3.2.8 on 2022-03-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_one_liner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreference",
            name="platform_fee_percent",
            field=models.DecimalField(decimal_places=2, default=4.9, max_digits=3),
        ),
    ]
