# Generated by Django 3.2.8 on 2022-04-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_historicaluserpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserpreference",
            name="donation_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicaluserpreference",
            name="thank_you_message",
            field=models.TextField(default="Thank you for the support! 🎉"),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="donation_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="thank_you_message",
            field=models.TextField(default="Thank you for the support! 🎉"),
        ),
    ]
