# Generated by Django 3.2.8 on 2022-04-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_auto_20220405_0516"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaluserpreference",
            old_name="donation_message",
            new_name="donation_description",
        ),
        migrations.RenameField(
            model_name="userpreference",
            old_name="donation_message",
            new_name="donation_description",
        ),
    ]
