# Generated by Django 3.2.8 on 2022-05-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_auto_20220405_0521"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserpreference",
            name="notify_comment_replies",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicaluserpreference",
            name="notify_donations",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicaluserpreference",
            name="notify_following_posts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicaluserpreference",
            name="notify_marketing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicaluserpreference",
            name="notify_memberships",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicaluserpreference",
            name="notify_post_comments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="notify_comment_replies",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="notify_donations",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="notify_following_posts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="notify_marketing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="notify_memberships",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="notify_post_comments",
            field=models.BooleanField(default=True),
        ),
    ]
