# Generated by Django 3.2.8 on 2022-06-02 07:29

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_creatoractivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatoractivity",
            name="data",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
