# Generated by Django 3.2.8 on 2022-06-26 11:24

from django.db import migrations, models
import memberships.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_creatoractivity_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits, dashes and underscores only.",
                max_length=150,
                unique=True,
                validators=[
                    memberships.users.validators.ASCIIUsernameValidator(),
                    memberships.users.validators.validate_username,
                ],
                verbose_name="username",
            ),
        ),
    ]
