# Generated by Django 3.2.8 on 2022-07-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserpreference",
            name="ip_address",
            field=models.GenericIPAddressField(null=True, verbose_name="IP address"),
        ),
    ]
