# Generated by Django 3.2.8 on 2022-07-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_historicaluserpreference_ip_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="one_liner",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
