# Generated by Django 3.2.14 on 2023-01-05 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0003_auto_20220725_0043"),
        ("memberships", "0005_auto_20221021_1318"),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[("payment_failed", "Payment Failed")], max_length=15
                    ),
                ),
                ("payload", models.JSONField()),
                (
                    "donation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_events",
                        to="donations.donation",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_events",
                        to="memberships.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "application_events",
                "ordering": ("-created_at",),
                "default_related_name": "application_events",
            },
        ),
    ]
