# Generated by Django 3.2.8 on 2022-07-21 00:02

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("processing", "Processing"),
                            ("linked", "Linked"),
                        ],
                        default="created",
                        max_length=16,
                    ),
                ),
                ("account_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=255)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("Private Limited", "Private Limited"),
                            ("Partnership", "Partnership"),
                            ("Proprietorship", "Proprietorship"),
                            ("Individual", "Individual"),
                            ("LLP", "Llp"),
                        ],
                        default="Individual",
                        max_length=32,
                    ),
                ),
                ("ifsc", models.CharField(max_length=16)),
                ("is_active", models.BooleanField(default=True)),
                ("external_id", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "bank_accounts",
                "ordering": ("-created_at",),
                "default_related_name": "bank_accounts",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("created", "Created"),
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("donation", "Donation"),
                            ("subscription", "Subscription"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("netbanking", "Netbanking"),
                            ("upi", "Upi"),
                            ("wallet", "Wallet"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("INR", "Indian Rupee")],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=7),
                ),
                ("external_id", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "payments",
                "ordering": ("-created_at",),
                "default_related_name": "payments",
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("processed", "Processed"),
                            ("settled", "Settled"),
                        ],
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("INR", "Indian Rupee")],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=7),
                ),
                ("external_id", models.CharField(max_length=255)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="payments.bankaccount",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "db_table": "payouts",
                "ordering": ("-created_at",),
                "default_related_name": "payouts",
            },
        ),
    ]
