# Generated by Django 3.2.14 on 2022-08-15 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payout",
            name="bank_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payouts",
                to="payments.bankaccount",
            ),
        ),
    ]
