name: github-pages

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'

jobs:
  build-deploy:
    name: Build and push the built bundle to its own branch for ease of deployment
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install

      - name: Build
        working-directory: ./frontend
        run: yarn generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          publish_branch: frontend-build
