# Generated by Django 3.2.8 on 2021-12-26 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("socialaccount", "0003_extra_data_default_dict"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "social_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord_users",
                        to="socialaccount.socialaccount",
                    ),
                ),
            ],
            options={
                "db_table": "discord_users",
                "ordering": ("-created_at",),
                "default_related_name": "discord_users",
            },
        ),
        migrations.CreateModel(
            name="DiscordServer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("external_id", models.CharField(max_length=50)),
                (
                    "social_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord_servers",
                        to="socialaccount.socialaccount",
                    ),
                ),
            ],
            options={
                "db_table": "discord_servers",
                "ordering": ("-created_at",),
                "default_related_name": "discord_servers",
            },
        ),
        migrations.CreateModel(
            name="DiscordRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("external_id", models.CharField(max_length=50)),
                (
                    "discord_server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="integrations.discordserver",
                    ),
                ),
            ],
            options={
                "db_table": "discord_roles",
                "ordering": ("-created_at",),
                "default_related_name": "discord_roles",
            },
        ),
    ]
