# Generated by Django 3.2.8 on 2022-07-21 00:02

from django.db import migrations, models
import django_extensions.db.fields
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                ("is_published", models.BooleanField(default=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
            ],
            options={
                "db_table": "comments",
                "ordering": ("-created_at",),
                "default_related_name": "comments",
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("images", "Images"),
                            ("attachments", "Attachments"),
                            ("link", "Link"),
                        ],
                        max_length=16,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, upload_to="uploads/content/"
                    ),
                ),
                ("link", models.URLField(blank=True)),
                ("link_og", models.JSONField(blank=True, default=None, null=True)),
                ("link_embed", models.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                "db_table": "contents",
                "ordering": ("-created_at",),
                "default_related_name": "contents",
            },
        ),
        migrations.CreateModel(
            name="ContentFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("image", "Image"), ("attachment", "Attachment")],
                        default="image",
                        max_length=16,
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, upload_to="uploads/content/"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(blank=True, upload_to="uploads/content/"),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "content_files",
                "ordering": ["order"],
                "default_related_name": "content_files",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        allow_duplicates=True,
                        blank=True,
                        editable=False,
                        populate_from="title",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("all_members", "All Members"),
                            ("allowed_tiers", "Allowed Tiers"),
                        ],
                        default="public",
                        max_length=16,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "posts",
                "ordering": ("-created_at",),
                "default_related_name": "posts",
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "emoji",
                    models.CharField(choices=[("heart", "Heart")], max_length=16),
                ),
            ],
            options={
                "db_table": "reactions",
                "ordering": ("-created_at",),
                "default_related_name": "reactions",
            },
        ),
    ]
