# Generated by Django 3.2.8 on 2021-11-13 09:03

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211028_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='uploads/content/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='link_embed',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='link_og',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
