# Generated by Django 3.2.8 on 2022-04-07 17:40

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_auto_20220327_0154"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("images", "Images"),
                    ("attachments", "Attachments"),
                    ("link", "Link"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ContentFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, upload_to="uploads/content/"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(blank=True, upload_to="uploads/content/"),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="posts.content",
                    ),
                ),
            ],
            options={
                "db_table": "content_files",
                "ordering": ("-created_at",),
                "default_related_name": "content_files",
            },
        ),
    ]
