# Generated by Django 3.2.8 on 2022-04-06 22:32

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_auto_20220327_0154"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="level",
            field=models.PositiveIntegerField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="lft",
            field=models.PositiveIntegerField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="posts.comment",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="rght",
            field=models.PositiveIntegerField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="tree_id",
            field=models.PositiveIntegerField(
                db_index=True, default=None, editable=False
            ),
            preserve_default=False,
        ),
    ]
