# Generated by Django 3.2.8 on 2022-04-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_auto_20220407_2310"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfile",
            name="type",
            field=models.CharField(
                choices=[("image", "Image"), ("attachment", "Attachment")],
                default="image",
                max_length=16,
            ),
        ),
    ]
