# Generated by Django 3.2.8 on 2022-04-07 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_auto_20220407_0402"),
        ("posts", "0007_contentfile_type"),
    ]

    operations = []
