# Generated by Django 3.2.8 on 2021-10-27 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import djmoney.models.fields
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("donations", "0001_initial"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        auto_created=True,
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("processing", "Processing"), ("linked", "Linked")],
                        default="processing",
                        max_length=16,
                    ),
                ),
                ("account_name", models.CharField(max_length=255)),
                ("mobile_number", models.CharField(max_length=10)),
                ("account_number", models.CharField(max_length=255)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("Private Limited", "Private Limited"),
                            ("Partnership", "Partnership"),
                            ("Proprietorship", "Proprietorship"),
                            ("Individual", "Individual"),
                            ("LLP", "Llp"),
                        ],
                        default="Individual",
                        max_length=32,
                    ),
                ),
                ("beneficiary_name", models.CharField(max_length=255)),
                ("ifsc", models.CharField(max_length=16)),
                ("is_active", models.BooleanField(default=True)),
                ("external_id", models.CharField(max_length=12)),
                (
                    "beneficiary_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bank_accounts",
                "ordering": ("-created_at",),
                "abstract": False,
                "default_related_name": "bank_accounts",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        auto_created=True,
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("created", "Created"),
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("donation", "Donation"),
                            ("subscription", "Subscription"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("INR", "Indian Rupee")],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=7),
                ),
                ("external_id", models.CharField(max_length=255)),
                (
                    "buyer_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="donations.donation",
                    ),
                ),
                (
                    "seller_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "ordering": ("-created_at",),
                "abstract": False,
                "default_related_name": "payments",
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        auto_created=True,
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("processed", "Processed"),
                        ],
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("INR", "Indian Rupee")],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(decimal_places=2, max_digits=7),
                ),
                ("external_id", models.CharField(max_length=255)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="payments.bankaccount",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "db_table": "payouts",
                "ordering": ("-created_at",),
                "abstract": False,
                "default_related_name": "payouts",
            },
        ),
    ]
