# Generated by Django 3.2.8 on 2021-11-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_auto_20211028_0636"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("card", "Card"),
                    ("netbanking", "Netbanking"),
                    ("upi", "Upi"),
                    ("wallet", "Wallet"),
                ],
                default="card",
                max_length=16,
            ),
            preserve_default=False,
        ),
    ]
