# Generated by Django 3.2.8 on 2021-11-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_auto_20211106_1906"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="external_id",
            field=models.CharField(max_length=255),
        ),
    ]
