# Generated by Django 3.2.8 on 2022-02-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_bankaccount_external_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="beneficiary_name",
        ),
        migrations.RemoveField(
            model_name="bankaccount",
            name="mobile_number",
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("processing", "Processing"),
                    ("linked", "Linked"),
                ],
                default="created",
                max_length=16,
            ),
        ),
    ]
