# Generated by Django 3.2.8 on 2022-05-05 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_alter_payout_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payout",
            name="payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payout",
                to="payments.payment",
            ),
        ),
    ]
