# Generated by Django 3.2.8 on 2022-06-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_alter_payout_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payout",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("processed", "Processed"),
                    ("settled", "Settled"),
                ],
                default="scheduled",
                max_length=16,
            ),
        ),
    ]
