# Generated by Django 3.2.14 on 2022-10-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_discorduser_external_id"),
        ("memberships", "0003_auto_20220725_0043"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltier",
            name="discord_role",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="integrations.discordrole",
            ),
        ),
        migrations.AddField(
            model_name="tier",
            name="discord_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tiers",
                to="integrations.discordrole",
            ),
        ),
    ]
